excluded:
    - Pods
    - Pexeso/Presentation/Storyboards

variable_name:
  min_length: 2
  max_length: 50

line_length:
  warning: 150
  error: 200

disabled_rules:
    - nesting
    - identifier_name
